= Constraints

Constraints provide a way of specifying and enforcing conditions at a
column level in a table schema definition and enforcing them at write time.

== CREATE CONSTRAINT

Constraints can be created within the column definition, or as part
of the table properties.

The main syntax to define a constraint is as follows:

[source,bnf]
----
CREATE TABLE keyspace.table (
	name text,
	i int CHECK (condition) (AND (condition))*
	...,

);
----

As shown in this syntax, more than one constraint can be defined for a given column using the AND keyword.

== ALTER CONSTRAINT

Altering a constraint is done by following the alter column CQL syntax:
[source,bnf]
----
ALTER TABLE [IF EXISTS] <table> ALTER [IF EXISTS] <column> CHECK <condition>;
----

== DROP CONSTRAINT
And DROP can be used to drop constraints for a column as well.
[source,bnf]
----
ALTER TABLE [IF EXISTS] <table> ALTER [IF EXISTS] <column> DROP CHECK;
----

== AVAILABLE CONSTRAINTS

=== SCALAR CONSTRAINT

Defines a comparator against a numeric type. It support all numeric types supported in Cassandra, with all the regular
comparators.

For example, we can define constraints that ensure that i is bigger or equal than 100 but smaller than 1000.

[source,bnf]
----
CREATE TABLE keyspace.table (
	name text,
	i int CHECK i < 1000 AND i > 100
	...,
);
----

Altering that constraint can be done with:

----
ALTER TABLE keyspace.table ALTER i CHECK i >= 500;
----

Finally, the constraint can be removed:

----
ALTER TABLE keyspace.table ALTER i DROP CHECK;
----

=== LENGTH CONSTRAINT

Defines a condition that checks the length of text or binary type.

For example, we can create a constraint that checks that name can't be longer than 256 characters:

----
CREATE TABLE keyspace.table (
	name text CHECK LENGTH(name) < 256
	...,
);
----

Altering that constraint can be done with:

----
ALTER TABLE keyspace.table ALTER name LENGTH(name) < 512;
----

Finally, the constraint can be removed:

----
ALTER TABLE keyspace.table ALTER name DROP CHECK;
----

=== NOT_NULL CONSTRAINT

Defines a condition that checks if a column is null. This nullity check is only performed against the value that has been passed on the insert statement, which means that if no value is present on the INSERT statement no constraint check is performed. The reason behind this is to support partial update insert statements, without forcing the user to specify the constrained column every time even if there is no intention of updating it. For the strict evaluation of this constraint against all the insert statements, please check the STRICTLY_NOT_NULL constraint instead.

----
CREATE TABLE keyspace.table (
	name text CHECK NOT_NULL(name)
	...,
);
----

Altering that constraint can be done with:

----
ALTER TABLE keyspace.table ALTER name CHECK NOT_NULL(name);
----

Finally, the constraint can be removed:

----
ALTER TABLE keyspace.table ALTER name DROP CHECK;
----

=== STRICTLY_NOT_NULL CONSTRAINT

Defines a condition that checks if a column is null in every insert statement.

----
CREATE TABLE keyspace.table (
	name text CHECK STRICTLY_NOT_NULL(name)
	...,
);
----

Altering that constraint can be done with:

----
ALTER TABLE keyspace.table ALTER name CHECK STRICTLY_NOT_NULL(name);
----

Finally, the constraint can be removed:

----
ALTER TABLE keyspace.table ALTER name DROP CHECK;
----