= Constraints

Constraints provide a way of specifying and enforcing conditions at a
column level in a table schema definition and enforcing them at write time.

== CREATE CONSTRAINT

Constraints can be created within the column definition, or as part
of the table properties.

The main syntax to define a constraint is as follows:

[source,bnf]
----
CREATE TABLE keyspace.table (
	name text,
	i int CHECK (condition) (AND (condition))*
	...,

);
----

As shown in this syntax, more than one constraint can be defined for a given column using the AND keyword.

== ALTER CONSTRAINT

Altering a constraint is done by following the alter column CQL syntax:
[source,bnf]
----
ALTER TABLE [IF EXISTS] <table> ALTER [IF EXISTS] <column> CHECK <condition>;
----

== DROP CONSTRAINT
And DROP can be used to drop constraints for a column as well.
[source,bnf]
----
ALTER TABLE [IF EXISTS] <table> ALTER [IF EXISTS] <column> DROP CHECK;
----

== AVAILABLE CONSTRAINTS

=== SCALAR CONSTRAINT

Defines a comparator against a numeric type. It support all numeric types supported in Cassandra, with all the regular
comparators.

For example, we can define constraints that ensure that i is bigger or equal than 100 but smaller than 1000.

[source,bnf]
----
CREATE TABLE keyspace.table (
	name text,
	i int CHECK i < 1000 AND i > 100
	...,
);
----

Altering that constraint can be done with:

----
ALTER TABLE keyspace.table ALTER i CHECK i >= 500;
----

Finally, the constraint can be removed:

----
ALTER TABLE keyspace.table ALTER i DROP CHECK;
----

=== LENGTH CONSTRAINT

Defines a condition that checks the length of text or binary type.

For example, we can create a constraint that checks that name can't be longer than 256 characters:

----
CREATE TABLE keyspace.table (
	name text CHECK LENGTH(name) < 256
	...,
);
----

Altering that constraint can be done with:

----
ALTER TABLE keyspace.table ALTER name LENGTH(name) < 512;
----

Finally, the constraint can be removed:

----
ALTER TABLE keyspace.table ALTER name DROP CHECK;
----

=== NOT_NULL constraint

Defines a condition that checks if a column is null. This nullity check is only performed against the value that
has been passed on the insert statement, which means that if no value is present on the `INSERT` statement
no constraint check is performed. The reason behind this is to support partial update insert statements,
without forcing the user to specify the constrained column every time even if there is no intention of updating it.
For the strict evaluation of this constraint against all the modification statements,
please check the `STRICTLY_NOT_NULL` constraint instead.

----
CREATE TABLE keyspace.table (
	name text CHECK NOT_NULL(name)
	...,
);
----

Altering that constraint can be done with:

----
ALTER TABLE keyspace.table ALTER name CHECK NOT_NULL(name);
----

Finally, the constraint can be removed:

----
ALTER TABLE keyspace.table ALTER name DROP CHECK;
----

=== STRICTLY_NOT_NULL constraint

Defines a condition that checks if a column is null in every modification statement.

----
CREATE TABLE keyspace.table (
	name text CHECK STRICTLY_NOT_NULL(name)
	...,
);
----

For example, imagine there is this table:

----
CREATE TABLE ks.tb (
    id int,
    cl int,
    col1 int CHECK NOT_NULL(col1),
    col2 int CHECK NOT_NULL(col2),
    PRIMARY KEY (id, cl)
);
----

Then, a user inserts data into this table:

----
INSERT INTO ks.tb (id, cl, col1) VALUES (1, 2, 3);
----

When selected, a user sees:

----
SELECT * FROM ks.tb;

 id | cl | col1 | col2
----+----+------+------
  1 |  2 |    3 | null

----

Because a user did not specify `col2` in the `INSERT` statement above, `null` will be present. Cassandra would need to
_read-before-write_ to check if `col2` is `null` or not, which is not desirable, and we can not know in advance what the
value of `col2` is without looking.

Similar situation happens when we go to update:

----
UPDATE ks.tb SET col1 = 5 WHERE id = 1 AND cl = 2;
----

This would, again, set `col1` to `5`, but we would keep `col2` unmodified, which means that `col2` might again contain `null`.

However, if `ks.tb` was created like this,

----
CREATE TABLE ks.tb (
    id int,
    cl int,
    col1 int CHECK STRICTLY_NOT_NULL(col1),
    col2 int CHECK STRICTLY_NOT_NULL(col2),
    PRIMARY KEY (id, cl)
);
----

then this statement would fail:

----
INSERT INTO ks.tb (id, cl, col1) VALUES (1, 2, 3);
... [Invalid query] message="Column 'col2' has to be specified as part of this query."
----

Altering that constraint can be done with:

----
ALTER TABLE keyspace.table ALTER name CHECK STRICTLY_NOT_NULL(name);
----

Finally, the constraint can be removed:

----
ALTER TABLE keyspace.table ALTER name DROP CHECK;
----

For both `NOT_NULL` and `STRICTLY_NOT_NULL`, we can not remove the value of such column:

----
DELETE col2 FROM ks.tb WHERE id = 1 AND cl = 2;
... [Invalid query] message="Column 'col2' can not be set to null."
----

`NOT_NULL` and `STRICTLY_NOT_NULL` checks can not be defined at once, this is illegal:

----
CREATE TABLE ks.tb (
    id int,
    cl int,
    col1 int CHECK STRICTLY_NOT_NULL(col1) AND NOT_NULL(col1,
    PRIMARY KEY (id, cl)
);
----

Additionally, `NOT_NULL` and `STRICTLY_NOT_NULL` can not be specified on any primary key column.
